"{} as aikido teacher, clear face, casual, white training clothes with black hakama and black belt, loose hair, photorealistic detailed, intricate, cinematic lighting, 8k, focused, extreme details, super resolution, wind, realistic",
"{} underwater surrounded by tropical fish and coral reefs",
"{} in a red dress traveling in indonesia, clear face",
"{} smelling a flower, roses everywhere, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha",
"{} swimming underwater, surrounded by tropical fish and coral reefs",
"{} by ilya kuvshinov, clear face, cloudy sky background lush landscape illustration concept art anime key visual by makoto shinkai, sharp focus",
"{} wearing superman's uniform, cute face",
"{} having a cup of coffee",
"{} surfing on the sea, clear face",
"a portrait of {} as gandalf the grey, with wizard hat and robe, from the movie of lord of the rings, hdr, cinematic shot",
"{} as a jedi with lightsaber, star wars, by artgerm and moebius, beautiful, hyperrealism, highly detailed, 8k, intricate, closeup, dynamic dramatic dark moody lighting, shadows, artstation, concept art, octane render, 8k",
"a portrait of a {}, clear face, posing with a tabby cat, by justin gerard and greg rutkowski, digital art, realistic painting, dnd, character design, trending on artstation",
"{}, neutral face, wearing blue silk dress with diamond studded lily iris flowers, fashion model style, high resolution, realistic anatomy photography",
"{} wearing creative jewel suit with high collar and purple blue gemstone wings and glass crown, fashion model style, high resolution, realistic anatomy photography",
"{} dressed as mario, digital art, hyperdetailed, illustration, trending on artstation, matte painting, CGSociety, pinterest",
"a cute little {} in the shape of a ball, pixar style, 4k, portrait, forest background, cinematic lighting, award winning creature portrait photography",
"{} beautiful Gold Knightess redhead hysterically laughing out loud and dancing, visible eye laughter lines, visible smile lines, funny weird facial expression, tightly closed eyes, open gaping mouth, close up face, long flowing hair, photorealistic, wearing intricately designed high chroma tank top, perfect clean defined underarms, chiaroscuro solid colors, divine elegance, perfect teeth, beautiful intricate halo",
"{} as a Disney Princess",
"{} leading an army on a holy war on Mars, clear face",
"a happy {} catching a tennis ball underwater, clear face, closeup shot in the style of Seth Casteel, highly detailed underwater photography",
"{} wearing dune costume, closeup, in a rocky desert landscape, from the movie dune",
"{} wearing blue silk dress diamond studded lily iris flowers, clear face, fashion model style, high resolution, realistic anatomy photography",
"{} wearing creative jewel suit with high collar and purple blue gemstone wings and glass crown, fashion model style, high resolution, realistic anatomy photography",
"a face portrait of Cyberpunk {} in a tokyo street, clear face, beautiful eyes, Dark Aesthetic, Neon sunset background, indoor in the style of blade runner, stands illuminated by greens neon lights, crowded with cyborgs photorealistic background",
